# Configurar entorno mediante archivo .env
services:
  db:
    image: postgres:17.5
    container_name: spptze-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

volumes:
  db-data:
